
CREATE DATABASE IF NOT EXISTS StarUniverse;
USE StarUniverse;

CREATE TABLE IF NOT EXISTS Usuario(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  sobrenome VARCHAR(45) NULL,
  CPF CHAR(11) UNIQUE NOT NULL,
  email VARCHAR(80) UNIQUE NULL, constraint ctEmail check(email like'%@%.%'),
  senha VARCHAR(100) NOT NULL
  );


CREATE TABLE IF NOT EXISTS Musica (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nome VARCHAR(45) NULL
  );


CREATE TABLE IF NOT EXISTS Votacao (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  data DATETiME DEFAULT CURRENT_TIMESTAMP(),
  Motivo VARCHAR(500) NOT NULL,
  fkMusica INT NOT NULL,
  fkUsuario INT NOT NULL,
  CONSTRAINT ctfkMusica FOREIGN KEY (fkMusica) REFERENCES Musica(id),
  CONSTRAINT ctfkUsuario FOREIGN KEY (fkUsuario) REFERENCES Usuario(id) 
  );